/*
 * Copyright (c) 2024. Lyzev
 * All rights reserved.
 */
package dev.lyzev.skija.util

import org.lwjgl.opengl.GL11
import org.lwjgl.opengl.GL12

enum class PixelStore(val value: Int) {
    PACK_SWAP_BYTES(GL11.GL_PACK_SWAP_BYTES),
    PACK_LSB_FIRST(GL11.GL_PACK_LSB_FIRST),
    PACK_ROW_LENGTH(GL11.GL_PACK_ROW_LENGTH),
    PACK_IMAGE_HEIGHT(GL12.GL_PACK_IMAGE_HEIGHT),
    PACK_SKIP_PIXELS(GL11.GL_PACK_SKIP_PIXELS),
    PACK_SKIP_ROWS(GL11.GL_PACK_SKIP_ROWS),
    PACK_SKIP_IMAGES(GL12.GL_PACK_SKIP_IMAGES),
    PACK_ALIGNMENT(GL11.GL_PACK_ALIGNMENT),
    UNPACK_SWAP_BYTES(GL11.GL_UNPACK_SWAP_BYTES),
    UNPACK_LSB_FIRST(GL11.GL_UNPACK_LSB_FIRST),
    UNPACK_ROW_LENGTH(GL11.GL_UNPACK_ROW_LENGTH),
    UNPACK_IMAGE_HEIGHT(GL12.GL_UNPACK_IMAGE_HEIGHT),
    UNPACK_SKIP_PIXELS(GL11.GL_UNPACK_SKIP_PIXELS),
    UNPACK_SKIP_ROWS(GL11.GL_UNPACK_SKIP_ROWS),
    UNPACK_SKIP_IMAGES(GL12.GL_UNPACK_SKIP_IMAGES),
    UNPACK_ALIGNMENT(GL11.GL_UNPACK_ALIGNMENT)
}
